#!/usr/bin/env bash

SCRIPTPATH=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

dir=$1
shift 1

tmp=$(mktemp /tmp/AXXXXXXXX)
node ${SCRIPTDIR}/index.js $dir '' > ${tmp}

TARGET=java-gen
# flags:
#  s source folder
#  a annotation
#  E omit hashcode and equal
#  S omit toString
#  R remove old output
#  P use primitive
java -jar ${SCRIPTDIR}/external/jsonschema2pojo*/jsonschema2pojo-cli-0.4.11.jar -s ${tmp} -a GSON -E -S -R -P -t ${TARGET} "$@"

rm -f ${TARGET}/$(basename $tmp).java
